provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  url-ping:
    annotations:
      test: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
    lang: python
    handler: ./sample/url-ping
    image: ${DOCKER_USER:-alexellis2}/url-ping:0.3
    environment:
      debug: true
  #    requests:
  #      memory: 32Mi
  #    limits:
  #      memory: 64Mi

  # skip_build is useful for deploying pre-existing images from stack.yml
  stronghash:
    skip_build: true
    image: ghcr.io/openfaas/alpine:latest
    fprocess: "sha512sum"
    environment:
      fprocess: sha512sum
    secrets:
      - test1
      - test2

  nodejs-echo:
    lang: node
    handler: ./sample/nodejs-echo
    image: ${DOCKER_USER:-alexellis2}/nodejs-echo:0.2

  # Example usage:
  #
  # curl 127.0.0.1:8080/function/shrink-image --data-binary @big.png > smaller.png
  shrink-image:
    lang: dockerfile
    handler: ./sample/imagemagick
    image: ${DOCKER_USER:-alexellis2}/imagemagick-resizer:0.3
    fprocess: "convert - -resize 50% fd:1"

  ruby-echo:
    lang: ruby
    handler: ./sample/ruby-echo
    image: ${DOCKER_USER:-alexellis2}/ruby-echo:0.3
